More weirdness - fdb session:

    yonatan@pinkelephant:~/src/play/las3r$ fdb bin/repl.swf 
    Adobe fdb (Flash Player Debugger) [build 0]
    Copyright (c) 2004-2007 Adobe, Inc. All rights reserved.
    Attempting to launch and connect to Player using URL
    bin/repl.swf
    Player connected; session starting.
    Set breakpoints and then type 'continue' to resume the session.
    [SWF] /home/yonatan/src/play/las3r/bin/repl.swf - 713,303 bytes after decompression
    (fdb) br evalCurrentInput
    Breakpoint 1 at 0x2138: file Repl.as, line 317
    (fdb) c
    [SWF] /home/yonatan/src/play/las3r/bin/repl.swf/[[DYNAMIC]]/1 - 273,291 bytes after decompression
    [SWF] /home/yonatan/src/play/las3r/bin/repl.swf/[[DYNAMIC]]/2 - 2,175 bytes after decompression
    [SWF] /home/yonatan/src/play/las3r/bin/repl.swf/[[DYNAMIC]]/3 - 556 bytes after decompression

Typed (fn [] 0) into the repl.

    Breakpoint 1, evalCurrentInput() at Repl.as:317
     317   		protected function evalCurrentInput():void{
    (fdb) br loadBytes
    Breakpoint 2 at 0x853: file ByteLoader.as, line 96
    (fdb) br Compiler.as:306
    Breakpoint 3: file Compiler.as, line 306
    (fdb) c
    Breakpoint 3, Compiler.as:306
     306   				throw new CompilerError(msg);
    (fdb) print msg
    $1 = "CompilerError at Evaluated Source:1:  VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds."
    (fdb) bt
    #0   this = [Object 4067262593, class='com.las3r.runtime::Compiler'].Compiler/analyze(context=[Object 4045414041, class='com.las3r.runtime::C'], form=[Object 4067633321, class='com.las3r.runtime::List'], name=null) at Compiler.as:306
    #1   this = [Object 4067262593, class='com.las3r.runtime::Compiler'].Compiler/loadForm(form=[Object 4067633321, class='com.las3r.runtime::List'], callback=[Function 4067295841, name='Function'], errorCallback=[Function 4067295809, name='Function']) at Compiler.as:143
    #2   this = [Object 4046565441, class='global'].Function/<anonymous>(result=null) at Compiler.as:119
    #3   this = [Object 4067262593, class='com.las3r.runtime::Compiler'].Compiler/load(rdr=[Object 4046597057, class='com.las3r.io::LineNumberingPushbackReader'], _onComplete=[Function 4067295777, name='Function'], _onFailure=[Function 4067295809, name='Function'], _progress=[Function 4046595265, name='Function'], sourcePath=null, sourceName=null) at Compiler.as:131
    #4   this = [Object 4132503713, class='com.las3r.runtime::RT'].RT/evalNextInQ() at RT.as:401
    #5   this = [Object 4132503713, class='com.las3r.runtime::RT'].RT/queueEvalUnit(unit=[Object 4066054593, class='com.las3r.runtime::ReaderEvalUnit']) at RT.as:369
    #6   this = [Object 4132503713, class='com.las3r.runtime::RT'].RT/evalStr(src="(fn [] 0)", onComplete=[Function 4067295969, name='Function'], progress=null, onFailure=[Function 4047350593, name='Function']) at RT.as:364
    #7   this = [Object 4131545153, class='com.las3r.repl::Repl'].Repl/evalCurrentInput() at Repl.as:331
    #8   this = [Object 4131545153, class='com.las3r.repl::Repl'].Repl/onInputTextInput(e=[Object 4045658769, class='flash.events::TextEvent']) at Repl.as:293
    (fdb) 

loadBytes doesn't get called, so the VerifyError isn't coming from las3r generated bytecode???
